# Changes here will be overwritten by Copier
_commit: v0.12.0
_src_path: gh:srv6d/python-copier
author_email: m@rvinvogt.com
author_name: Marvin Vogt
author_username: srv6d
codecov_badge_token: DPOGLYZ26N
copyright_holder: German Edge Cloud GmbH & Co. KG
copyright_holder_email: copyright@gec.io
display_codecov_badge: true
package_name: anycastd
project_description: A daemon to manage anycasted services based on status checks.
project_license: Apache License 2.0
project_name: anycastd
project_slug: anycastd
python_versions:
- '3.11'
- '3.12'
repository_namespace: gecio

