---
name: Build

on:
  release:
    types: [published]

permissions:
  id-token: write
  attestations: write
  contents: write
  packages: write

env:
  COLUMNS: 120

jobs:
  build-wheels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v4
      - name: Build
        run: pdm build
      - name: Attest Build Provenance
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: dist/anycastd-*
      - name: Upload Build Artifacts
        run: >-
          gh release upload "${GITHUB_REF_NAME}"
          dist/anycastd-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-container-image:
    needs: build-wheels
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    steps:
      - uses: docker/setup-buildx-action@v3

      - name: Container Registry Login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Download Release Wheel
        run: >-
          gh release download ${GITHUB_REF_NAME}
          --pattern '*.whl'
          --output anycastd.whl
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Build & Push Image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm/v7,linux/arm64

      - name: Attest Build Provenance
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
