---
name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: >-
    ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number
    || github.sha }}
  cancel-in-progress: true

env:
  COLUMNS: 120

jobs:
  lint:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python_version: ["3.11", "3.12"]
        nox_session:
          - ruff
          - mypy
          - lockfile
          - pytest
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python_version }}
      - run: pip3 install nox
      - run: nox -s ${{ matrix.nox_session }}
  spellcheck:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip3 install codespell
      - uses: codespell-project/codespell-problem-matcher@v1
      - name: check for typos
        run: codespell src/ tests/ README.md
