---
name: Check Links

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * 0

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check for broken links
        id: lychee
        uses: lycheeverse/lychee-action@v1
      - name: Create Issue From File
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
