---
name: Publish

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  COLUMNS: 120

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v4
      - name: Publish to PyPI
        run: pdm publish
