---
name: Publish

on:
  workflow_run:
    workflows: [Build]
    types: [completed]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Create Dist Directory
        run: mkdir dist

      - name: Download Relase Sdist and Wheel
        run: gh release download ${GITHUB_REF_NAME} --pattern "anycastd-*" --dir dist
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
