---
name: Test

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: >-
    ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number
    || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

jobs:
  pytest:
    name: pytest (Python ${{ matrix.python_version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.11", "3.12"]
      fail-fast: false
    env:
      PYTHON: ${{ matrix.python_version }}
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true
      - run: uv python install ${{ matrix.python_version }}
      - uses: extractions/setup-just@v2

      - run: just test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.5.0
        with:
          files: ./coverage.xml
          env_vars: PYTHON
          use_oidc: true
          fail_ci_if_error: true
