---
name: Test

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: >-
    ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number
    || github.sha }}
  cancel-in-progress: true

env:
  COLUMNS: 120

permissions:
  contents: read
  id-token: write

jobs:
  test:
    name: test with Python ${{ matrix.python_version }}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python_version: ["3.11", "3.12"]
      fail-fast: false
    env:
      PYTHON: ${{ matrix.python_version }}
    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python_version }}
      - run: pip3 install nox
      - run: nox -s test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.5.0
        with:
          files: ./coverage.xml,!./nox
          env_vars: PYTHON
          use_oidc: true
          fail_ci_if_error: true
