---
name: Verify

on:
  push:
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.11"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
      - run: uv python install ${{ env.PYTHON_VERSION }}
      - uses: extractions/setup-just@v2

      - run: just lint
  check-lockfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
      - run: uv python install ${{ env.PYTHON_VERSION }}
      - uses: extractions/setup-just@v2

      - run: just check-lockfile
  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
      - run: uv python install ${{ env.PYTHON_VERSION }}
      - uses: extractions/setup-just@v2

      - run: just type-check
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: check for typos
        uses: crate-ci/typos@v1.25.0
