---
name: Verify

on:
  push:
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.11"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: true
      - run: pip3 install nox
      - run: nox -s lint
  check-lockfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: true
      - run: pip3 install nox
      - run: nox -s lockfile
  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: true
      - run: pip3 install nox
      - run: nox -s mypy
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: check for typos
        uses: crate-ci/typos@v1.24.5
