---
name: Verify

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

env:
  COLUMNS: 120

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v4
        with:
          python-version: "3.11"
      - run: pip3 install nox
      - run: nox -s lint
  spellcheck:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: check for typos
        uses: crate-ci/typos@v1.24.5
